set_project("DedicatedHelpersClient")
set_version("0.1.0")
set_languages("c++20")
set_toolchains("clang-cl")

add_requires("minhook", "zydis 4.1.1")

target("memorylib")
    set_kind("static")
    add_files("../memorylib/src/memorylib.cpp")
    add_packages("minhook", "zydis")
    add_includedirs("../memorylib/include", {public = true})
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX", "UNICODE", "_UNICODE")
    add_cxxflags("/EHsc", "/W4", "/permissive-")
    add_syslinks("kernel32")

target("DedicatedHelpersClient")
    set_kind("shared")
    add_files("src/main.cpp", "src/directory_client.cpp")
    add_deps("memorylib")
    add_packages("minhook")
    add_includedirs("../memorylib/include")
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX", "UNICODE", "_UNICODE")
    add_cxxflags("/EHsc", "/W4", "/permissive-")
    add_ldflags("/SUBSYSTEM:WINDOWS")
    add_syslinks("kernel32", "user32", "shell32", "winhttp")
